version: 2.1
jobs:
  go-test:
    environment:
      GO111MODULE: "on"
      CONSUL_VERSION: 1.8.0
      VAULT_VERSION: 1.4.2
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:latest
    working_directory: /go/src/github.com/hashicorp/hcat
    steps:
      - checkout
      - restore_cache:
          keys:
            - ct-modcache-v1-{{ checksum "go.mod" }}
      - run: |
          curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
          unzip consul.zip
          sudo cp consul /usr/local/bin/
      - run: |
          curl -sLo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
          unzip vault.zip
          sudo cp vault /usr/local/bin/
      - run: |
          go test ./...
      - save_cache:
          key: ct-modcache-v1-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod

workflows:
  version: 2
  go-tests:
    jobs:
      - go-test
